### ISSUE TITLE
Single versions of node / npm 

### ISSUE THREAD

**Issue by willtemperley** [Maxim-Mazurok/SAX-TypeScript#7]
Great lib btw. Only very minor issue is it's pinned to single versions of node and npm (see warnings below). Would you be able to change that to something more flexible? NodeJS 12 is EOL anyway. https://endoflife.date/nodejs

```console
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'sax-ts@1.2.11',
npm WARN EBADENGINE   required: { node: '12.19.0', npm: '6.14.8' },
npm WARN EBADENGINE   current: { node: 'v16.14.2', npm: '9.1.1' }
npm WARN EBADENGINE
}
```

**Comment by Maxim-Mazurok** [comment]
Thank you! It's a bit unmaintained as I'm not using it myself. The way I
use the engines section for my personal projects is I pin it to a specific
version that I'm 100% sure works so that I don't have to think about it.
Probably doesn't make that much sense for a lib, I agree. I guess it'll be
safe to assume that anything above 12.19.0 will work fine (unless they
brake it with esm stuff or something) so that's probably what I'm going to
set as a requirement, same with npm, 6.14.8 and above. LMK if that'll work
or if you have a better idea that wouldn't require much
involvement/maintenance, thanks again!

**Comment by willtemperley** [comment]
Yes that'd be great if you could, thanks! Seems to work fine in v16.14.2 and on Cloudflare Workers so I don't think it's using any weird node-specific APIs

**Comment by Maxim-Mazurok** [comment]
Fixed in https://github.com/Maxim-Mazurok/sax-ts/commit/b2c6da4cfe8ddb832264b55c6eaecd7554f12bd3
Published https://www.npmjs.com/package/sax-ts/v/1.2.12
Thanks for reporting this, consider giving this repo a star ;) Cheers!

**Comment by willtemperley** [comment]
Sweet all warnings now gone :) starred, thanks!
